logging:
  config: classpath:logback-spring.xml
spring:
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址（默认为localhost）
    host: localhost
    # Redis服务器连接端口(默认为6379)
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: 123456
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
    # 连接超时时间（毫秒）默认是2000
    timeout: 5000
server:
  port: 8083
